/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *                         // ELECTROGRAVITY
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "clock.h"
#include "stdbool.h"
// for new version of cubeIDE 1.13 (other versions do not require)

__attribute__((weak)) void _close(void){}
__attribute__((weak)) void _lseek(void){}
__attribute__((weak)) void _read(void){}
__attribute__((weak)) void _write(void){}


void GPIO_CONFIG (void)
{
	// port A  // PIN 0
   RCC->AHB1ENR |= (1<<0);   // clock for port A
   GPIOA->MODER |= (0<<0);  // make pin0 as input
   GPIOA->MODER |= (0<<1);
   GPIOA->PUPDR |= (1<<1);  // pull down



}


void interrupt_config (void)

{

	RCC->APB2ENR |= (1<<14); //enable SYSCNFG
	SYSCFG ->EXTICR [0] &= ~(0xf<<0);  // (0<<0) (0<<1) (0<<2) (0<<3) // configure the exti0 for pin 0
	EXTI ->IMR |= (1<<0); // disable the mask on line0 (EXTI0)
	EXTI->RTSR |= (0<<0); // disable rising edge
	EXTI->FTSR |= (1<<0);// enable falling edge
	NVIC_SetPriority (EXTI0_IRQn, 5); // priority
	NVIC_EnableIRQ (EXTI0_IRQn); // enable interrupt


}
uint32_t add = 0;
int flag = 0;
void EXTI0_IRQHandler (void){

	if ( EXTI->PR & (1<<0))  // if my interrupt is triggered ,
	{
		flag = 1;
		EXTI->PR |= (1<<0); // clear the interrupt flag


	}

}

void delay (uint32_t delay)
{

	while (delay--);
}

int main(void)
{
	clock_config ();
	//clock_Systickconfig (72000);
	GPIO_CONFIG ();
	interrupt_config ();
	while(1)
	{




		if (flag)

		{
			delay (3000000);
			add++;
			flag =0;

		}
   }
}






